export enum RequestType {
  NEW_ROUTE = 'NEW_ROUTE',
  JOIN_EXISTING = 'JOIN_EXISTING',
  TEMPORARY = 'TEMPORARY',
  RECURRING = 'RECURRING'
}

export enum RouteStatus {
  PENDING_TEEN = 'PENDING_TEEN',
  PENDING_PARENT = 'PENDING_PARENT',
  PENDING_DRIVER = 'PENDING_DRIVER',
  PENDING_ADMIN = 'PENDING_ADMIN',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum UserRole {
  PARENT = 'PARENT',
  DRIVER = 'DRIVER',
  TEEN = 'TEEN',
  ADMIN = 'ADMIN'
}

export enum LocationType {
  SCHOOL = 'SCHOOL',
  BUSINESS = 'BUSINESS',
  RESIDENTIAL = 'RESIDENTIAL',
  BUS_STOP = 'BUS_STOP',
  LANDMARK = 'LANDMARK',
  OTHER = 'OTHER'
}

export enum StopType {
  PICKUP = 'PICKUP',
  DROP = 'DROP'
}

export enum TripStatus {
  SCHEDULED = 'SCHEDULED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum RideStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PICKUP_PENDING = 'PICKUP_PENDING',
  PICKED_UP = 'PICKED_UP',
  DROP_PENDING = 'DROP_PENDING',
  DROPPED_OFF = 'DROPPED_OFF',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}

export enum RouteType {
  ADMIN_CREATED = 'ADMIN_CREATED',
  DRIVER_CREATED = 'DRIVER_CREATED',
  PARENT_CREATED = 'PARENT_CREATED',
  TEEN_REQUESTED = 'TEEN_REQUESTED'
}

export enum RouteFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY'
}

export enum PricingType {
  FIXED = 'FIXED',
  PER_KM = 'PER_KM',
  ZONE_BASED = 'ZONE_BASED'
}

export enum TransactionType {
  TOPUP = 'TOPUP',
  RIDE_PAYMENT = 'RIDE_PAYMENT',
  REFUND = 'REFUND',
  REWARD = 'REWARD'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}

export enum BuddyStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  BLOCKED = 'BLOCKED'
}

export enum InviteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED'
}

export enum InviteType {
  PARENT_TO_TEEN = 'PARENT_TO_TEEN',
  TEEN_TO_PARENT = 'TEEN_TO_PARENT'
}

export enum DocumentType {
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  AADHAR_CARD = 'AADHAR_CARD',
  VEHICLE_RC = 'VEHICLE_RC',
  INSURANCE = 'INSURANCE',
  POLICE_VERIFICATION = 'POLICE_VERIFICATION'
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
} 